- arguments:
    entity: EIN
    word-neighbor-max-bottom-dist: 0
    word-neighbor-max-left-dist: 20
    word-neighbor-max-right-dist: 20
    word-neighbor-max-top-dist: 15
    word-neighbors:
    - Employer's FED ID number
    - Employer identification number (EIN)
    x-position: 0.0
    y-position: 0.0
  name: EIN
  weights:
    entity: 0.5
    word-neighbors: 0.5
    x-position: 0.0
    y-position: 0.0
