data_dir: data/full/w2/train/multi
label_path: data/full/w2/train/multi_label.csv
queries_path: configs/multi_queries.yaml
error_path: logs/multi_pos_off_error.yaml
neighbor_off: false
position_off: true
entity_off: false