data_dir: data/full/w2/train/multi
label_path: data/full/w2/train/multi_label.csv
queries_path: configs/multi_queries.yaml
error_path: logs/multi_nei_off_error.yaml
neighbor_off: true
position_off: false
entity_off: false